### ISSUE TITLE
trakt account hasnt been authenticated

### ISSUE THREAD

**Issue by cicerocf** [trakt-for-plex/configuration#29]
I am having issue authenticating to trakt
attempting to setup the plugin for Plex on FreeNAS
I have the channel created, and i have created the account at Trakt.tv
Lnked my plex and my trakt account here:
http://trakt-for-plex.github.io/configuration/#/configuration/accounts?id=1
Plex has a green check  while Trakt has a minus sign...  this an issue?
Going into Plex and attempting to push or pull, I am getting the following error 
"trakt account hasn't been authenticated"
I have ensured the pin at the site and the pin in the Sync Settings match.
I  
so what am i doing wrong?

**Comment by fuzeman** [comment]
> Plex has a green check while Trakt has a minus sign... this an issue?

Yeah, scrobbling and syncing probably won't work until they both display green check marks.

---------

Have you tried generating a new pin for your Trakt.tv account *(via https://trakt.tv/pin/478)* and re-authenticating via the configuration site?

You don't need to worry about having the pins match between the configuration site and channel settings, the configuration site will correctly update the plugin authentication itself.

**Comment by cicerocf** [comment]
I have many times... never has gone green.. should i just delete the account and try again?    
also please note, i have posted this a few different locations....

thanks

**Comment by fuzeman** [comment]
Interesting... maybe an error is silently happening in the plugin.

Could you post the latest plugin log file (after attempting to authenticate again)? see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by cicerocf** [comment]
Running FreeNas...  no logs at all...
root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Logs/PMS Plugin Logs # ls
root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Logs/PMS Plugin Logs #

**Comment by cicerocf** [comment]
I do have it set to debug and still no logs...

**Comment by cicerocf** [comment]
I have uninstalled trakt.tv (from the channel icon) and re-installed it, following the FreeBSD instructions:
https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20FreeBSD%20%28Terminal%29

Same results, in the configuration page, Plex is green check, and the trakt is a grey minus

**Comment by fuzeman** [comment]
I've confirmed the plugin works on FreeNAS 9.10.2, and the log files are written into that path:
```
root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Logs/PMS Plugin Logs # ls -l                                              
[...]
-rw-r--r--  1 plex  plex   40255 Jan 10 09:48 com.plexapp.plugins.trakttv.log
-rw-r--r--  1 plex  plex   31595 Jan 10 09:45 com.plexapp.plugins.trakttv.log.1
-rw-rw-rw-  1 plex  plex   38289 Jan 10 09:44 com.plexapp.plugins.trakttv.log.2
[...]
```

--------------

Might want to check:
 - Ensure the drive containing "plexdata" isn't full (might explain why logs aren't being written)
 - Ensure the Trakt.tv plugin isn't installed under the system plugins directory at:

    ```
    /usr/pbi/plexmediaserver-[...]/share/plexmediaserver/Resources/Plug-ins-[...]/
    ```
 - Ensure the `Trakttv.bundle` directory is owned by the "plex" user

    Can be fixed with:
    ```
    chown -R plex:plex Trakttv.bundle
    ```

If all that looks correct, post the contents of `[...]/Plex Media Server/Logs/Plex Media Server.log` right after Plex Media Server has been restarted. Hopefully that log file will have some more clues as to why the plugin isn't working correctly.

**Comment by cicerocf** [comment]
Not full
root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Logs/PMS Plugin
Logs # df -h
Filesystem                         Size    Used   Avail Capacity  Mounted on
volume1/jails/plexmediaserver_1     10T    3.4T    6.7T    34%    /

Not installed here:
root@plexmediaserver_1:/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-a17e99e
# ls
Fanart-TV.bundle        LastFM.bundle           Media-Flags.bundle
 PersonalMedia.bundle    PlexThemeMusic.bundle   System.bundle
WebClient.bundle
Framework.bundle        LocalMedia.bundle       MoviePosterDB.bundle
 PlexMovie.bundle        PlexVevo.bundle         TheMovieDB.bundle
HTbackdrops.bundle      LyricFind.bundle        OpenSubtitles.bundle
 PlexMusic.bundle        Scanners.bundle         TheTVDB.bundle


Directory and files owner and group are plex

root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Plug-in
Support/Data # ls -al *trakttv
total 60
drwxr-xr-x   5 plex  plex    8 Jan  7 21:18 .
drwxrwxrwx  35 plex  plex   35 Jan  3 19:38 ..
drwxr-xr-x   3 plex  plex    3 Jan  3 19:40 Backups
drwxr-xr-x   2 plex  plex    2 Jan  3 19:38 DataItems
-rw-r--r--   1 plex  plex  467 Jan  7 21:18 Dict
-rw-r--r--   1 plex  plex  126 Jan  7 21:33 HTTPCookies
drwxr-xr-x   3 plex  plex    3 Jan  3 19:38 Libraries
-rw-r--r--   1 plex  plex   55 Jan  3 19:52 StoredValues


Attempted to push to Trakt.tv and it failed due to authentication error

no data in logs

root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Logs/PMS Plugin
Logs # ls -al
total 17
drwxrwxrwx  2 plex  plex   2 Feb 11  2015 .
drwxrwxrwx  3 plex  plex  50 Jan  9 02:16 ..
[image: Inline image 1]

unable to find any information on the SSL3 error either...
My freenas does not have any SSL Certificates installed...

Carl

Points to Ponder
     If a virus is an invader, and your body is a defender, doctors are
really just paid mercenaries to aid the body in combat.

**Comment by fuzeman** [comment]
> Directory and files owner and group are plex
> 
> ```
> root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Plug-in
> Support/Data # ls -al *trakttv
> total 60
> drwxr-xr-x   5 plex  plex    8 Jan  7 21:18 .
> drwxrwxrwx  35 plex  plex   35 Jan  3 19:38 ..
> drwxr-xr-x   3 plex  plex    3 Jan  3 19:40 Backups
> drwxr-xr-x   2 plex  plex    2 Jan  3 19:38 DataItems
> -rw-r--r--   1 plex  plex  467 Jan  7 21:18 Dict
> -rw-r--r--   1 plex  plex  126 Jan  7 21:33 HTTPCookies
> drwxr-xr-x   3 plex  plex    3 Jan  3 19:38 Libraries
> -rw-r--r--   1 plex  plex   55 Jan  3 19:52 StoredValues
> ```

Did you check that `Plex Media Server/Plug-ins/Trakttv.bundle` (and sub-folders) are owned by `plex` as well? *(you've only shown the `Plug-in Support` directory here)*

> [image: Inline image 1]

Doesn't look like images attached in email responses come through to github.com, could you upload it in a comment to issue https://github.com/trakt-for-plex/configuration/issues/29?

> unable to find any information on the SSL3 error either...
> My freenas does not have any SSL Certificates installed...

Not sure what you are referring to? guessing it's related to the missing image above?

---------------

Sending me the `Plex Media Server/Logs/Plex Media Server.log` file right after restarting Plex Media Server might help me identify why the plugin isn't functioning correctly. Feel free to email it to me directly at me@dgardiner.net

**Comment by cicerocf** [comment]
text of the image I attempted to upload.

[Exception] Trakt account hasn‘t been authenticated

[Trakt.tv]_ssl.c:504: error14090086:SSL routines:ssl3_get,server,certificate:certificate verify failed (code: 1)

This was the error that I could not find...

I set Plex debug level to Verbose, and then restarted it..  but do not see anything of significance 
[Plex Media Server.txt](https://github.com/trakt-for-plex/configuration/files/700340/Plex.Media.Server.txt)

here i viewed the debug file from inside plex and copy/pasted it.

[insideplexlogs.txt](https://github.com/trakt-for-plex/configuration/files/700341/insideplexlogs.txt)

**Comment by fuzeman** [comment]
> [Trakt.tv]_ssl.c:504: error14090086:SSL routines:ssl3_get,server,certificate:certificate verify failed (code: 1)

This looks similar to an issue that has been recently fixed in [trakt.py](https://github.com/fuzeman/trakt.py): https://github.com/fuzeman/trakt.py/issues/52

You could try install the latest development release of the plugin which has this fix, available here: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

-------------

> I set Plex debug level to Verbose, and then restarted it.. but do not see anything of significance
> Plex Media Server.txt

Is this all that's displayed in the log file? maybe you need to enable `Enable Plex Media Server debug logging` as well?

I'm interested in any entries that mention the loading of the `com.plexapp.plugins.trakttv` plugin.

**Comment by cicerocf** [comment]
I failed at enabling Debug... I was enabling WEB debugging rather then SERVER debug...

Please let me know if you want me to proceed with the developer install...

Here are the correct debug logs and a quick clip that relates to Trakttv.bundle

Jan 14, 2017 16:05:35.022 [0x80b542c00] DEBUG - Starting plug-in /var/db/plexdata/Plex Media Server/Plug-ins/Trakttv.bundle.
Jan 14, 2017 16:05:35.022 [0x80a29cc00] DEBUG - Updating the list of agents known by the system.
Jan 14, 2017 16:05:35.022 [0x80a29cc00] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/agents
Jan 14, 2017 16:05:35.023 [0x80a29cc00] DEBUG - HTTP requesting GET http://127.0.0.1:45856/system/agents
Jan 14, 2017 16:05:35.023 [0x80b542c00] DEBUG - [com.plexapp.plugins.trakttv] Setting plug-in to always running (daemon mode).
Jan 14, 2017 16:05:35.025 [0x80b542c00] DEBUG - Starting file watcher for com.plexapp.plugins.trakttv
Jan 14, 2017 16:05:35.029 [0x80b542c00] DEBUG - Spawned plug-in com.plexapp.plugins.trakttv with PID 39232
Jan 14, 2017 16:05:35.029 [0x80b542c00] DEBUG - [com.plexapp.plugins.trakttv] Sending command: GET /:/prefixes
Jan 14, 2017 16:05:35.057 [0x80a29cc00] DEBUG - HTTP success requesting GET http://127.0.0.1:45856/system/agents
Jan 14, 2017 16:05:35.057 [0x80a29cc00] DEBUG - [com.plexapp.system] HTTP reply status 200, with 8048 bytes of content.
Jan 14, 2017 16:05:35.070 [0x80a29cc00] DEBUG - The system knows about 15 agents.
Jan 14, 2017 16:05:35.616 [0x809cbf400] DEBUG - Request: [127.0.0.1:42848] GET / (12 live) GZIP
Jan 14, 2017 16:05:35.616 [0x809cbf400] DEBUG - Authorization is disabled
Jan 14, 2017 16:05:35.618 [0x809cbf400] DEBUG - It took 0.0 sec to serialize a list with 20 elements.
Jan 14, 2017 16:05:35.619 [0x808f1b400] DEBUG - Completed: [127.0.0.1:42848] 200 GET / (12 live) GZIP 3ms 1299 bytes
Jan 14, 2017 16:05:35.668 [0x80b542800] DEBUG - Reading 515 bytes in the body, code is 200
Jan 14, 2017 16:05:35.669 [0x80b542800] DEBUG - [com.plexapp.plugins.unsupportedappstore] Plug-in running on port 42849.
Jan 14, 2017 16:05:35.669 [0x80b542800] DEBUG -  * Plug-in handles prefix: /video/unsupportedappstore
Jan 14, 2017 16:05:35.669 [0x80b542800] DEBUG - Read configuration for [com.plexapp.plugins.unsupportedappstore], had 1 prefixes
Jan 14, 2017 16:05:35.692 [0x80b542800] DEBUG - Starting plug-in /var/db/plexdata/Plex Media Server/Plug-ins/BitTorrent.bundle.
Jan 14, 2017 16:05:35.693 [0x80b542800] DEBUG - [com.plexapp.plugins.bittorrent] Setting plug-in to always running (daemon mode).
Jan 14, 2017 16:05:35.695 [0x80b542800] DEBUG - Starting file watcher for com.plexapp.plugins.bittorrent
Jan 14, 2017 16:05:35.698 [0x80b542800] DEBUG - Spawned plug-in com.plexapp.plugins.bittorrent with PID 39234
Jan 14, 2017 16:05:35.699 [0x80b542800] DEBUG - [com.plexapp.plugins.bittorrent] Sending command: GET /:/prefixes
Jan 14, 2017 16:05:36.386 [0x809cbfc00] DEBUG - Request: [127.0.0.1:42851] GET /system/messaging/clear_events/com.plexapp.plugins.trakttv (12 live) GZIP
Jan 14, 2017 16:05:36.386 [0x809cbfc00] DEBUG - Authorization is disabled
Jan 14, 2017 16:05:36.387 [0x809cbfc00] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/messaging/clear_events/com.plexapp.plugins.trakttv
Jan 14, 2017 16:05:36.388 [0x809cbfc00] DEBUG - HTTP requesting GET http://127.0.0.1:45856/system/messaging/clear_events/com.plexapp.plugins.trakttv
Jan 14, 2017 16:05:36.395 [0x809cbfc00] DEBUG - HTTP success requesting GET http://127.0.0.1:45856/system/messaging/clear_events/com.plexapp.plugins.trakttv
Jan 14, 2017 16:05:36.396 [0x809cbfc00] DEBUG - [com.plexapp.system] HTTP reply status 200, with 0 bytes of content.
Jan 14, 2017 16:05:36.396 [0x808f1b400] DEBUG - Completed: [127.0.0.1:42851] 200 GET /system/messaging/clear_events/com.plexapp.plugins.trakttv (12 live) GZIP 10ms 180 bytes
Jan 14, 2017 16:05:36.869 [0x80a29d400] DEBUG - Request: [127.0.0.1:42853] GET /:/plugins/com.plexapp.system/resourceHashes (12 live) GZIP
Jan 14, 2017 16:05:36.869 [0x80a29d400] DEBUG - Authorization is disabled
Jan 14, 2017 16:05:36.870 [0x80a29d400] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /:/plugins/com.plexapp.system/resourceHashes
Jan 14, 2017 16:05:36.871 [0x80a29d400] DEBUG - HTTP requesting GET http://127.0.0.1:45856/:/plugins/com.plexapp.system/resourceHashes
Jan 14, 2017 16:05:36.880 [0x80a29d400] DEBUG - HTTP success requesting GET http://127.0.0.1:45856/:/plugins/com.plexapp.system/resourceHashes
Jan 14, 2017 16:05:36.880 [0x80a29d400] DEBUG - [com.plexapp.system] HTTP reply status 200, with 13276 bytes of content.

[Plex Media Server.txt](https://github.com/trakt-for-plex/configuration/files/706319/Plex.Media.Server.txt)

**Comment by fuzeman** [comment]
> Please let me know if you want me to proceed with the developer install...

Yeah, try the development version of the plugin mentioned above. *(it still requires some more testing before stable release)*

----------------------

I couldn't find any issues in your log file, still have no idea why plugin log files aren't being written to the `PMS Plugin Logs` directory...

I'm going to do some more testing with FreeNAS 9.3 and Plex Media Server v1.0.0 later today to see if I can reproduce the issue you are encountering on your system.

**Comment by cicerocf** [comment]
installed the dev version, I am getting the same error...
Trakt account hasnt been authenticated

http://trakt-for-plex.github.io/configuration/#/configuration/accounts?id=1
Still shows a minus for Trakt and a green check for Plex
![trakt-for-plex github io_configuration](https://cloud.githubusercontent.com/assets/8641907/22093182/36b84cbc-ddc9-11e6-8f59-763ae159c535.JPG)
[Plex Media Server.txt](https://github.com/trakt-for-plex/configuration/files/715673/Plex.Media.Server.txt)

**Comment by fuzeman** [comment]
> http://trakt-for-plex.github.io/configuration/#/configuration/accounts?id=1
> Still shows a minus for Trakt and a green check for Plex

Did you re-authenticate your Trakt.tv account after installing the development version of the plugin?

------------

I wasn't able to reproduce the same issues you are encountering with the plugin in a virtual machine running FreeNAS 9.3 and Plex Media Server v1.0.0. I did encounter the same `certificate verify failed` error on the latest stable release, but updating to the current development version of the plugin does fix this issue...

**Comment by cicerocf** [comment]
How do I do this?
Did you re-authenticate your Trakt.tv account after installing the
development version of the plugin?
Just the pin number at https://trakt.tv/pin/478 ?

If so, then yes I did.

Points to Ponder
     If a virus is an invader, and your body is a defender, doctors are
really just paid mercenaries to aid the body in combat.

**Comment by fuzeman** [comment]
When you update the PIN for your account on the configuration site, are you clicking the save button afterwards? the status icon won't update until you send the changes to your server.

Can't think of anything else you could try to resolve this issue... without the plugin log files all I can do is take guesses at possible solutions and try reproduce the issue in virtual machines.

**Comment by cicerocf** [comment]
Ok, to be fair.. it doesnt look like a save icon... i didnt recognize it as
a floppy disk until after you said save and i started looking for a save
button

and i signed in.. i wouldnt think you would need to save....

ok i give up.. i just failed big time....

clicking the save button worked... i am able to push...  but no logging


root@plexmediaserver_1:/var/db/plexdata/Plex Media Server/Logs/PMS Plugin
Logs # ls -al
total 17
drwxrwxrwx  2 plex  plex   2 Feb 11  2015 .
drwxrwxrwx  3 plex  plex  50 Jan 24 13:42 ..


Points to Ponder
     If a virus is an invader, and your body is a defender, doctors are
really just paid mercenaries to aid the body in combat.
